<?php

/**
 * @file
 * Enhanced control over the CSS colores of any Block.
 *
 * Block color allows users to add colores to any block through the block's
 * configuration interface. This implementation is based on an alteration of
 * the Core block database table to leverage the Core Block API functions,
 * objects and structure.
 */

/**
 * Implements hook_permission().
 */
function block_background_color_permission() {
  return array(
    'administer block colores' => array(
      'title' => t('Administer block background color'),
      'description' => t('Set CSS background color for blocks.'),
    ),
  );
}

/**
 * Implements theme_preprocess_block().
 *
 * Extend block's colores with any user defined colores.
 
function block_background_color_preprocess_block(&$vars) {
  $block = $vars['block'];
  if (isset($block->background_color) && $block->background_color != '') {
    $vars['colores_array'] = array_merge($vars['colores_array'], explode(' ', $block->background_color));
  }
}
*/
/**
 * Implements hook_preprocess_HOOK().
 *
 * Extend panel block's colores with any user defined colores.
 */
function block_background_color_preprocess_panels_pane(&$vars) {
  if ($vars['pane']->type != 'block') {
    return;
  }
  // Infer the block's $module and $delta from the pane subtype.
  $block_parts = explode('-', $vars['pane']->subtype);
  // Load the block based on the block parts.
  $block = block_load($block_parts[0], $block_parts[1]);
  // Add a generic 'module type' pane color.
  $vars['colores_array'][] = drupal_html_color('pane-' . $block->module);
  // Add $background_color to the $colores_array.
  if (isset($block->background_color) && $block->background_color != '') {
    $vars['colores_array'] = array_merge($vars['colores_array'], explode(' ', $block->background_color));
  }
}

/**
 * Implements hook_form_alter().
 *
 * Alter block edit form to add configuration field.
 */
function block_background_color_form_alter(&$form, &$form_state, $form_id) {
  if (user_access('administer block colores') && ($form_id == 'block_admin_configure' || $form_id == 'block_add_block_form')) {
    // Load statically cached block object used to display the form.
    $block = block_load($form['module']['#value'], $form['delta']['#value']);

    $form['settings']['background_color'] = array(
      '#type' => 'textfield',
      '#title' => t('Color Hex'),
      '#default_value' => isset($block->background_color) ? $block->background_color : '',
      '#description' => t('Customize the background color of this block by adding color HEX.'),
      '#maxlength' => 255,
	  '#attributes' => array(
        'class' => array('color'),
      ),
	  '#attached' => array(
        'css' => array(drupal_get_path('module', 'block_background_color') . '/colorpicker/mcColorPicker.css'),
		'js' => array(drupal_get_path('module', 'block_background_color') . '/colorpicker/mcColorPicker.js'),
		
      ),
    );

    $form['#submit'][] = 'block_background_color_form_submit';
  }
}

/**
 * Helper function: additional submit callback for block configuration pages.
 *
 * Save supplied CSS colores.
 */
function block_background_color_form_submit($form, &$form_state) {
  if ($form_state['values']['form_id'] == 'block_admin_configure' || $form_state['values']['form_id'] == 'block_add_block_form') {
    // Only save if value has changed.
    if (isset($form_state['values']['background_color']) && $form['settings']['background_color']['#default_value'] != $form_state['values']['background_color'] && user_access('administer blocks')) {
      db_update('block')
        ->fields(array('background_color' => $form_state['values']['background_color']))
        ->condition('module', $form_state['values']['module'])
        ->condition('delta', $form_state['values']['delta'])
        ->execute();
      // Flush all context module cache to use the updated background_color.
      if (module_exists('context')) {
        cache_clear_all('context', 'cache', TRUE);
      }
    }
  }
}
